def drawHangedMan(attempts):
    if attempts == 0:
        print("________      ")
        print("|             ")
        print("|             ")
        print("|             ")
        print("|             ")
        print("|             ")
    elif attempts == 1:
        print("________      ")
        print("|      |      ")
        print("|             ")
        print("|             ")
        print("|             ")
        print("|             ")
    elif attempts == 2:
        print("________      ")
        print("|      |      ")
        print("|      0      ")
        print("|             ")
        print("|             ")
        print("|             ")
    elif attempts == 3:
        print("________      ")
        print("|      |      ")
        print("|      0      ")
        print("|      |      ")
        print("|             ")
        print("|             ")
    elif attempts == 4:
        print("________      ")
        print("|      |      ")
        print("|      0      ")
        print("|     /|      ")
        print("|             ")
        print("|             ")
    elif attempts == 5:
        print("________      ")
        print("|      |      ")
        print("|      0      ")
        print("|     /|\     ")
        print("|             ")
        print("|             ")
    elif attempts == 6:
        print("________      ")
        print("|      |      ")
        print("|      0      ")
        print("|     /|\     ")
        print("|     /       ")
        print("|             ")
    else:
        print("________      ")
        print("|      |      ")
        print("|      0      ")
        print("|     /|\     ")
        print("|     / \     ")
        print("|             ")
        print("¡Has sido ahorcado!")
        return True